import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import StarRatings from 'react-star-ratings'
import { ToastContainer, toast } from 'react-toast'
import Link from 'next/link'

export default function favorite({ data }) {
    const handleFavorite = (e) => {
        const myheader = new Headers()
        myheader.append("Content-Type", "application/json");



        const requestOptions = {
            method: 'DELETE',
            headers: myheader,
            redirect: 'follow'
        };

        fetch(`/api/books/${e}`, requestOptions)
            .then(response => response.text())
            .then(result => {
                const data_json = JSON.parse(result)
                if (data_json.success) {
                    toast.success("success remove book to Favorite !")
                } else {
                    toast.warn(`${data_json.message} / already deleted`)
                }
            })
            .catch(error => {
                toast.error(`Error ${error}`)
                console.log('error', error)
            });
    }
    return (

        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ToastContainer />
            <main className={styles.main}>
                <div className='is-align-self-flex-end'><Link href='/'>Back to Home</Link></div>

                <div className='columns'>
                    <div className='column'>
                        <table className='table'>
                            <thead>
                                <tr>
                                    <th>Number</th>
                                    <th>Title</th>
                                    <th>Thumbnail</th>
                                    <th>Author</th>
                                    <th>Rating</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {data.data.map((params, index) => (
                                    <tr key={params._id}>
                                        <td>{index + 1}</td>
                                        <td>{params.title}</td>
                                        <td><Image src={params.thumbnail} alt="thumnail books" height={50} width={50} /></td>
                                        <td>{params.author}</td>
                                        <td><StarRatings rating={(params.rating) ? parseInt(params.rating) : 0} starDimension='15' starSpacing='5px' /></td>
                                        <td><button className='button' onClick={() => handleFavorite(params.id)}>remove from Favorite</button></td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}

export async function getServerSideProps() {
    const res = await fetch(`${process.env.BASE_URL}/api/books`)
    const data = await res.json()

    return { props: { data } }
}